name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
template: |
  ## Cambios

  $CHANGES

  ## Contributors

  $CONTRIBUTORS

categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Fixes"
    labels:
      - "fix"
      - "bug"
  - title: "🧱 CI/CD"
    labels:
      - "ci"
      - "chore"
  - title: "🧪 Tests"
    labels:
      - "test"
  - title: "📚 Docs"
    labels:
      - "docs"

change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
no-changes-template: "- Sin cambios categorizados"

version-resolver:
  major:
    labels:
      - "major"
      - "breaking"
  minor:
    labels:
      - "feature"
      - "enhancement"
  patch:
    labels:
      - "fix"
      - "bug"
      - "chore"
      - "ci"
      - "docs"
      - "test"
  default: patch
